name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
    - uses: actions/checkout@v3
    - name: build
      run: ./script/build_ratel_manager.sh
    - name: upload
    - uses: actions/upload-artifact@v3
      with:
        path: ratelmanager/build/outputs/apk/release/*.apk
